# Generated by Django 4.2 on 2023-06-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attachments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('content', models.TextField(blank=True, null=True)),
                ('index', models.PositiveIntegerField(default=0)),
                ('attachments', models.ManyToManyField(blank=True, to='attachments.attachment')),
            ],
            options={
                'ordering': ['index'],
            },
        ),
    ]
